# Generated by Django 4.1.3 on 2022-11-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_recommended_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='status',
            field=models.CharField(default='Prestado', max_length=20),
        ),
    ]
